"""add primary_language and readme_content to repository

Revision ID: 0cace408cfcb
Revises: db4ec617231a
Create Date: 2026-08-08 13:48:10.130323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cace408cfcb'
down_revision: Union[str, Sequence[str], None] = 'db4ec617231a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository', sa.Column('primary_language', sa.String(length=50), nullable=True))
    op.add_column('repository', sa.Column('readme_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository', 'readme_content')
    op.drop_column('repository', 'primary_language')
    # ### end Alembic commands ###
