"""add symbol and import_edge tables

Revision ID: 1b4022cf53a1
Revises: 8ea51ae24200
Create Date: 2026-08-13 14:56:39.665020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b4022cf53a1'
down_revision: Union[str, Sequence[str], None] = '8ea51ae24200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_edge',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('source_file_id', sa.UUID(), nullable=False),
    sa.Column('target_file_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['file.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_file_id'], ['file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_edge_repository_id'), 'import_edge', ['repository_id'], unique=False)
    op.create_index(op.f('ix_import_edge_source_file_id'), 'import_edge', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_import_edge_target_file_id'), 'import_edge', ['target_file_id'], unique=False)
    op.create_table('symbol',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbol_file_id'), 'symbol', ['file_id'], unique=False)
    op.create_index(op.f('ix_symbol_repository_id'), 'symbol', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symbol_repository_id'), table_name='symbol')
    op.drop_index(op.f('ix_symbol_file_id'), table_name='symbol')
    op.drop_table('symbol')
    op.drop_index(op.f('ix_import_edge_target_file_id'), table_name='import_edge')
    op.drop_index(op.f('ix_import_edge_source_file_id'), table_name='import_edge')
    op.drop_index(op.f('ix_import_edge_repository_id'), table_name='import_edge')
    op.drop_table('import_edge')
    # ### end Alembic commands ###
