"""add retry_count to jobs

Revision ID: 8ea51ae24200
Revises: e16b1adfee9a
Create Date: 2026-08-08 21:11:20.570123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ea51ae24200'
down_revision: Union[str, Sequence[str], None] = 'e16b1adfee9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'jobs',
        sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'retry_count')
    # ### end Alembic commands ###
